#!/usr/bin/env python3
"""Generate breed markdown files - Part 2: More breeds E-Z and file output."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_breeds_data import BREEDS, mk, write_md, body, OUT

B = BREEDS.append

B(mk("Egyptian Mau","egyptian-mau","Felis catus","The Egyptian Mau is the only naturally spotted domestic cat breed, with gooseberry green eyes and incredible speed.","Egypt","12-15 years","8-14 lbs (3.6-6.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Medium-short, silky, fine with glossy sheen",["Silver","Bronze","Smoke"],["Spotted tabby"],["Gooseberry green"],2,1,4,3,3,3,5,"rare",["shorthair","rare","intelligent","playful"],["spotted","fastest-domestic-cat","ancient-breed"],["CFA","TICA","FIFe"],["abyssinian","bengal","ocicat","savannah"],["bengal","ocicat","abyssinian"],False,100))

B(mk("European Shorthair","european-shorthair","Felis catus","The European Shorthair is a natural breed from Europe with a sturdy build and excellent hunting abilities.","Europe (Sweden/Finland)","15-20 years","9-14 lbs (4.1-6.4 kg)","7-11 lbs (3.2-5 kg)","9-11 inches (23-28 cm)","shorthair","Short, dense, glossy, and weather-resistant",["All natural colors"],["Tabby","Solid","Tortoiseshell","Bicolor"],["Green","Gold","Copper","Blue","Odd-eyed"],3,1,4,2,4,4,4,"common",["shorthair","popular","playful"],["natural-breed","european-origin","mouser","hardy"],["FIFe","WCF"],["american-shorthair","british-shorthair"],["american-shorthair","british-shorthair"],False,100))

B(mk("Exotic Shorthair","exotic-shorthair","Felis catus","The Exotic Shorthair is essentially a short-haired Persian with the same sweet, gentle personality.","United States","12-15 years","9-14 lbs (4.1-6.4 kg)","7-12 lbs (3.2-5.4 kg)","10-12 inches (25-30 cm)","shorthair","Short, thick, dense, plush, and soft teddy bear coat",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["Copper","Gold","Blue","Odd-eyed"],3,2,2,1,4,4,3,"uncommon",["shorthair","calm","popular"],["flat-face","persian-relative","low-energy"],["CFA","TICA","FIFe","GCCF"],["persian","british-shorthair","scottish-fold"],["persian","british-shorthair"],False,45))

B(mk("Foldex","foldex","Felis catus","The Foldex combines folded ears with a round, plush body for a uniquely Canadian breed.","Canada","12-15 years","7-13 lbs (3.2-5.9 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Short, dense, and plush teddy bear coat",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],3,2,2,2,4,4,4,"rare",["shorthair","rare","calm"],["folded-ears","canadian-origin","plush"],["CCA-AFC"],["scottish-fold","exotic-shorthair","british-shorthair"],["scottish-fold","exotic-shorthair"],False,100))

B(mk("German Rex","german-rex","Felis catus","The German Rex is one of the oldest curly-coated breeds with a silky, wavy coat and gentle personality.","Germany","10-15 years","7-10 lbs (3.2-4.5 kg)","5-8 lbs (2.3-3.6 kg)","8-10 inches (20-25 cm)","shorthair","Short, silky, and wavy with a plush feel",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor"],["All colors"],1,1,4,3,4,4,5,"very-rare",["shorthair","rare","hypoallergenic","playful"],["curly-coat","german-origin","rex","hypoallergenic"],["FIFe","WCF"],["cornish-rex","devon-rex","selkirk-rex"],["cornish-rex","devon-rex"],False,100))

B(mk("Havana Brown","havana-brown","Felis catus","The Havana Brown is a rare breed with a stunning mahogany-brown coat and vivid green eyes.","United Kingdom","12-15 years","6-10 lbs (2.7-4.5 kg)","5-8 lbs (2.3-3.6 kg)","8-10 inches (20-25 cm)","shorthair","Short to medium, smooth, glossy, and rich in color",["Mahogany brown","Chestnut brown"],["Solid"],["Green"],2,1,3,3,4,4,4,"very-rare",["shorthair","rare"],["brown-coat","rare-breed","people-oriented"],["CFA","TICA"],["siamese","burmese","russian-blue"],["burmese","bombay"],False,100))

B(mk("Highlander","highlander","Felis catus","The Highlander is a unique breed with curled ears, a short tail, and a wild, distinctive appearance.","United States","10-15 years","10-20 lbs (4.5-9.1 kg)","8-14 lbs (3.6-6.4 kg)","10-14 inches (25-36 cm)","shorthair","Short to medium; dense and resilient",["All colors and patterns"],["Tabby","Solid","Tortoiseshell","Bicolor"],["All colors"],3,2,4,2,4,4,5,"very-rare",["shorthair","rare","playful","large"],["curled-ears","bobbed-tail","wild-look","hybrid"],["TICA"],["american-curl","american-bobtail","bengal"],["american-bobtail","bengal"],False,100))

B(mk("Himalayan","himalayan","Felis catus","The Himalayan is a Persian with Siamese colorpoints, combining a luxurious long coat with striking blue eyes.","United States","9-15 years","9-14 lbs (4.1-6.4 kg)","7-11 lbs (3.2-5 kg)","10-12 inches (25-30 cm)","longhair","Long, thick, silky, and flowing with dense undercoat",["Seal point","Blue point","Chocolate point","Lilac point","Flame point","Cream point"],["Colorpoint"],["Deep blue"],4,5,2,2,3,3,3,"common",["longhair","popular","calm"],["colorpoint","persian-type","flat-face","blue-eyes"],["CFA","TICA","FIFe","GCCF"],["persian","siamese","ragdoll","birman"],["persian","ragdoll","birman"],False,50))

B(mk("Japanese Bobtail","japanese-bobtail","Felis catus","The Japanese Bobtail has a distinctive pom-pom tail and is celebrated as a symbol of good luck in Japan.","Japan","12-16 years","6-10 lbs (2.7-4.5 kg)","5-8 lbs (2.3-3.6 kg)","8-9 inches (20-23 cm)","shorthair","Soft, silky, and medium-short without noticeable undercoat",["Calico","Bicolor","Tortoiseshell","Solid"],["Calico","Bicolor","Tortoiseshell","Tabby","Solid"],["All colors","Odd-eyed common"],2,1,5,4,5,4,5,"rare",["shorthair","rare","playful","vocal"],["bobbed-tail","lucky-cat","japanese-origin","pom-pom-tail"],["CFA","TICA","FIFe"],["american-bobtail","manx","kurilian-bobtail"],["american-bobtail","manx"],False,100))

B(mk("Javanese","javanese","Felis catus","The Javanese is a colorpoint longhair breed related to the Balinese and Siamese, elegant and vocal.","United States","10-15 years","5-10 lbs (2.3-4.5 kg)","5-8 lbs (2.3-3.6 kg)","8-10 inches (20-25 cm)","longhair","Silky, fine, medium-length single coat",["Lynx point","Tortie point","Red/Cream point"],["Colorpoint with lynx or tortie markings"],["Deep blue"],2,2,4,4,4,4,5,"rare",["longhair","vocal","intelligent"],["colorpoint","siamese-relative","balinese-relative"],["CFA"],["balinese","siamese","oriental-longhair"],["balinese","oriental-longhair","siamese"],False,100))

B(mk("Khao Manee","khao-manee","Felis catus","The Khao Manee is an ancient Thai breed with a pure white coat and striking diamond-like eyes.","Thailand","10-14 years","8-12 lbs (3.6-5.4 kg)","6-8 lbs (2.7-3.6 kg)","10-12 inches (25-30 cm)","shorthair","Short, smooth, close-lying, and glossy white",["Pure white"],["Solid white"],["Blue","Gold","Green","Odd-eyed"],2,1,3,3,4,4,4,"very-rare",["shorthair","rare","intelligent"],["white-cat","thai-origin","odd-eyed","royal-breed"],["TICA","CFA"],["siamese","oriental-shorthair","turkish-angora"],["turkish-angora","foreign-white"],False,100))

B(mk("Korat","korat","Felis catus","The Korat is a rare Thai breed with a heart-shaped face and silver-blue coat, symbolizing good fortune.","Thailand","10-15 years","6-10 lbs (2.7-4.5 kg)","5-8 lbs (2.3-3.6 kg)","9-13 inches (23-33 cm)","shorthair","Short, fine, glossy with silver tips creating halo effect",["Silver-tipped blue"],["Solid with silver tipping"],["Peridot green"],2,1,3,3,3,3,5,"rare",["shorthair","rare","intelligent"],["blue-coat","thai-origin","good-luck","heart-face"],["CFA","TICA","FIFe","GCCF"],["russian-blue","chartreux","british-shorthair"],["russian-blue","chartreux"],False,100))

B(mk("Kurilian Bobtail","kurilian-bobtail","Felis catus","The Kurilian Bobtail is a natural Russian breed with a distinctive pom-pom tail and excellent fishing skills.","Russia (Kuril Islands)","15-20 years","11-15 lbs (5-6.8 kg)","8-12 lbs (3.6-5.4 kg)","9-12 inches (23-30 cm)","shorthair","Dense, plush, water-resistant double coat",["Red","Gray","Brown tabby","All colors"],["Tabby","Solid","Tortoiseshell","Bicolor"],["Gold","Green","Copper"],3,2,4,2,4,4,5,"rare",["shorthair","rare","playful","large"],["bobbed-tail","russian-origin","fishing-cat"],["TICA","FIFe","WCF"],["japanese-bobtail","american-bobtail","maine-coon"],["japanese-bobtail","maine-coon"],False,100))

B(mk("LaPerm","laperm","Felis catus","The LaPerm has a unique curly, permed-looking coat and an affectionate, people-oriented personality.","United States","10-15 years","8-12 lbs (3.6-5.4 kg)","6-8 lbs (2.7-3.6 kg)","6-10 inches (15-25 cm)","shorthair","Curly, springy ringlets; plush and soft texture",["All colors and patterns"],["Tabby","Tortoiseshell","Calico","Solid"],["All colors"],2,2,3,2,5,5,4,"rare",["shorthair","rare","hypoallergenic","playful"],["curly-coat","rex-type","hypoallergenic"],["CFA","TICA","FIFe"],["cornish-rex","devon-rex","selkirk-rex"],["selkirk-rex","cornish-rex"],False,100))

B(mk("Lykoi","lykoi","Felis catus","The Lykoi or Werewolf Cat has a partially hairless roan coat giving it a wolf-like appearance.","United States","12-15 years","6-12 lbs (2.7-5.4 kg)","4-8 lbs (1.8-3.6 kg)","8-10 inches (20-25 cm)","shorthair","Partially hairless with roan pattern; sparse coat that molts seasonally",["Black roan"],["Roan"],["Gold","Green"],2,2,3,2,4,4,5,"very-rare",["shorthair","rare","hypoallergenic","intelligent"],["werewolf-cat","roan-coat","unique","rare"],["TICA"],["sphynx","devon-rex","cornish-rex"],["sphynx","devon-rex"],False,100))

B(mk("Maine Coon","maine-coon","Felis catus","The Maine Coon is the gentle giant of cats, known for its large size, tufted ears, and dog-like personality.","United States (Maine)","12-15 years","15-25 lbs (6.8-11.3 kg)","8-15 lbs (3.6-6.8 kg)","10-16 inches (25-41 cm)","longhair","Heavy, shaggy, water-resistant double coat; longer on ruff and tail",["Brown tabby","All colors"],["Tabby","Solid","Tortoiseshell","Bicolor","Calico"],["Gold","Green","Copper","Blue","Odd-eyed"],4,3,3,3,5,5,5,"common",["longhair","popular","large","playful","intelligent"],["gentle-giant","tufted-ears","dog-like","largest-domestic-breed"],["CFA","TICA","FIFe","GCCF"],["norwegian-forest-cat","siberian","ragdoll","ragamuffin"],["norwegian-forest-cat","siberian","ragdoll"],True,4))

B(mk("Manx","manx","Felis catus","The Manx is a tailless or short-tailed breed from the Isle of Man with a rounded appearance and dog-like loyalty.","Isle of Man","8-14 years","10-14 lbs (4.5-6.4 kg)","8-10 lbs (3.6-4.5 kg)","7-10 inches (18-25 cm)","shorthair","Double coat that is short, dense, and plush",["All colors and patterns"],["Tabby","Solid","Tortoiseshell","Calico","Bicolor"],["Gold","Copper","Green","Hazel","Blue"],3,2,3,2,5,5,5,"uncommon",["shorthair","rare","intelligent","playful"],["tailless","rounded-appearance","dog-like"],["CFA","TICA","GCCF","FIFe"],["japanese-bobtail","american-bobtail","cymric"],["american-bobtail","japanese-bobtail"],False,55))

B(mk("Minskin","minskin","Felis catus","The Minskin is a short-legged breed with sparse fur points, tiny and uniquely patterned.","United States","12-15 years","4-6 lbs (1.8-2.7 kg)","4-6 lbs (1.8-2.7 kg)","5-7 inches (13-18 cm)","hairless","Sparse fur mainly on points; body nearly hairless and warm",["All colors and patterns"],["Point-restricted fur"],["All colors"],1,2,3,2,5,4,4,"very-rare",["hairless","rare","playful"],["short-legs","hairless","designer-breed","small"],["TICA"],["munchkin","sphynx","bambino","devon-rex"],["munchkin","sphynx","bambino"],False,100))

B(mk("Minuet (Napoleon)","minuet","Felis catus","The Minuet (Napoleon) combines Munchkin short legs with Persian beauty for a small, sweet companion.","United States","12-15 years","5-9 lbs (2.3-4.1 kg)","5-8 lbs (2.3-3.6 kg)","5-7 inches (13-18 cm)","shorthair","Dense, plush; also comes in longhair variety",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],3,2,2,2,5,5,4,"very-rare",["shorthair","rare","calm","small"],["short-legs","persian-type","cuddly","designer-breed"],["TICA"],["munchkin","persian","exotic-shorthair"],["munchkin","exotic-shorthair"],False,100))

B(mk("Munchkin","munchkin","Felis catus","The Munchkin is known for its short legs from a natural genetic mutation with a playful personality.","United States","12-15 years","6-9 lbs (2.7-4.1 kg)","4-8 lbs (1.8-3.6 kg)","5-7 inches (13-18 cm)","shorthair","Plush, dense; comes in both shorthair and longhair varieties",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],2,2,4,2,5,4,4,"uncommon",["shorthair","rare","playful"],["short-legs","dwarf-breed","playful"],["TICA"],["singapura","devon-rex","american-curl"],["singapura","minuet"],False,100))

B(mk("Nebelung","nebelung","Felis catus","The Nebelung is a rare longhaired breed with a shimmering blue-gray coat and vivid green eyes.","United States","11-16 years","8-12 lbs (3.6-5.4 kg)","7-10 lbs (3.2-4.5 kg)","9-13 inches (23-33 cm)","longhair","Semi-long, silky, fine with silver tipping creating shimmer effect",["Blue-gray with silver tips"],["Solid with silver tipping"],["Green","Yellow-green"],3,3,2,2,4,4,5,"very-rare",["longhair","rare","calm","intelligent"],["blue-coat","russian-blue-relative","shimmering","loyal"],["TICA","CFA"],["russian-blue","chartreux","maine-coon"],["russian-blue","chartreux"],False,100))

B(mk("Norwegian Forest Cat","norwegian-forest-cat","Felis catus","The Norwegian Forest Cat is a large, rugged natural breed from Scandinavia with a waterproof double coat.","Norway","14-16 years","13-22 lbs (5.9-10 kg)","9-13 lbs (4.1-5.9 kg)","9-12 inches (23-30 cm)","longhair","Long, thick, glossy, water-resistant double coat with wooly undercoat",["Brown tabby","All colors"],["Tabby","Solid","Tortoiseshell","Bicolor","Calico"],["Green","Gold","Copper","Blue"],4,3,3,2,5,5,5,"uncommon",["longhair","large","playful","intelligent","hypoallergenic"],["scandinavian","viking-cat","waterproof-coat"],["CFA","TICA","FIFe","GCCF"],["maine-coon","siberian","turkish-angora","ragdoll"],["maine-coon","siberian"],True,12))

B(mk("Ocicat","ocicat","Felis catus","The Ocicat has a wild spotted appearance but is 100% domestic, bred from Abyssinian, Siamese, and American Shorthair.","United States","12-18 years","12-15 lbs (5.4-6.8 kg)","8-11 lbs (3.6-5 kg)","9-11 inches (23-28 cm)","shorthair","Short, smooth, satiny, and close-lying",["Tawny","Chocolate","Cinnamon","Blue","Lavender","Fawn"],["Spotted tabby"],["All colors except blue"],2,1,4,3,5,5,5,"uncommon",["shorthair","intelligent","playful","large"],["wild-look","spotted","dog-like","no-wild-blood"],["CFA","TICA","FIFe","GCCF"],["bengal","egyptian-mau","abyssinian","savannah"],["bengal","egyptian-mau","toyger"],False,60))

B(mk("Oriental Longhair","oriental-longhair","Felis catus","The Oriental Longhair combines the elegant Oriental body type with a silky semi-long coat and plumed tail.","United Kingdom","12-15 years","8-12 lbs (3.6-5.4 kg)","5-10 lbs (2.3-4.5 kg)","9-11 inches (23-28 cm)","longhair","Semi-long, fine, and silky with a plumed tail",["300+ varieties"],["Solid","Tabby","Tortoiseshell","Bicolor","Smoke"],["Green","Blue","Odd-eyed"],3,2,4,5,4,4,5,"rare",["longhair","vocal","intelligent","rare"],["oriental-type","plumed-tail","vocal"],["TICA","FIFe","GCCF"],["oriental-shorthair","siamese","balinese","angora"],["balinese","turkish-angora","siamese"],False,100))

B(mk("Oriental Shorthair","oriental-shorthair","Felis catus","The Oriental Shorthair is sleek and elegant with oversized ears and comes in over 300 color varieties.","United Kingdom","12-15 years","8-12 lbs (3.6-5.4 kg)","5-10 lbs (2.3-4.5 kg)","9-11 inches (23-28 cm)","shorthair","Short, fine, silky, close-lying",["300+ varieties: Ebony, White, Blue, Chestnut, Lavender"],["Solid","Tabby","Tortoiseshell","Bicolor","Smoke"],["Green","Blue","Odd-eyed"],2,1,4,5,4,4,5,"uncommon",["shorthair","vocal","intelligent","playful"],["large-ears","sleek","300-colors","siamese-relative"],["CFA","TICA","FIFe","GCCF"],["siamese","oriental-longhair","balinese","javanese"],["siamese","balinese","peterbald"],False,65))

B(mk("Persian","persian","Felis catus","The Persian is one of the most recognizable breeds with its flat face and luxurious long coat.","Iran (Persia)","12-17 years","9-14 lbs (4.1-6.4 kg)","7-12 lbs (3.2-5.4 kg)","10-15 inches (25-38 cm)","longhair","Extremely long, thick, silky, and flowing with dense undercoat",["White","Black","Blue","Cream","Red","Silver","Golden"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint","Smoke"],["Copper","Blue","Green","Odd-eyed"],4,5,2,1,3,3,3,"common",["longhair","popular","calm"],["flat-face","luxurious-coat","calm","most-popular"],["CFA","TICA","FIFe","GCCF"],["himalayan","exotic-shorthair","ragdoll","birman"],["himalayan","exotic-shorthair","ragdoll"],True,6))

B(mk("Peterbald","peterbald","Felis catus","The Peterbald is an elegant hairless breed from Russia with a graceful Oriental-type build and affectionate nature.","Russia","12-15 years","7-14 lbs (3.2-6.4 kg)","6-10 lbs (2.7-4.5 kg)","8-12 inches (20-30 cm)","hairless","Hairless to velour to brush; varying degrees of hairlessness",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Colorpoint"],["All colors"],1,3,4,4,4,4,5,"rare",["hairless","rare","hypoallergenic","intelligent"],["hairless","russian-origin","oriental-type","hypoallergenic"],["TICA","FIFe","WCF"],["sphynx","don-sphynx","oriental-shorthair"],["sphynx","don-sphynx","oriental-shorthair"],False,100))

B(mk("Pixie-Bob","pixie-bob","Felis catus","The Pixie-Bob has a wild bobcat-like appearance with a short tail and often polydactyl paws.","United States","13-15 years","8-22 lbs (3.6-10 kg)","8-12 lbs (3.6-5.4 kg)","9-13 inches (23-33 cm)","shorthair","Dense, wooly, and weather-resistant; stands off the body",["Brown spotted tabby"],["Spotted tabby"],["Gold","Brown","Green"],3,2,3,2,5,5,5,"rare",["shorthair","rare","large","intelligent"],["bobcat-look","bobbed-tail","polydactyl","dog-like"],["TICA"],["american-bobtail","maine-coon","norwegian-forest-cat"],["american-bobtail","maine-coon"],False,100))

B(mk("Ragamuffin","ragamuffin","Felis catus","The Ragamuffin is a large, fluffy breed with an exceptionally sweet, puppy-like personality.","United States","12-16 years","15-20 lbs (6.8-9.1 kg)","10-15 lbs (4.5-6.8 kg)","9-12 inches (23-30 cm)","longhair","Medium-long, dense, silky, and plush; rabbit-like texture",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Calico","Colorpoint"],["All colors","Blue"],4,3,2,2,5,5,4,"rare",["longhair","rare","calm","large"],["gentle-giant","puppy-like","fluffy","ragdoll-relative"],["CFA","TICA"],["ragdoll","birman","maine-coon","himalayan"],["ragdoll","maine-coon"],False,100))

B(mk("Ragdoll","ragdoll","Felis catus","The Ragdoll is famous for going limp when held, with stunning blue eyes and a gentle, affectionate nature.","United States","12-17 years","12-20 lbs (5.4-9.1 kg)","8-15 lbs (3.6-6.8 kg)","9-11 inches (23-28 cm)","longhair","Semi-long, silky, soft with minimal undercoat; rabbit-like texture",["Seal","Blue","Chocolate","Lilac","Red","Cream"],["Colorpoint","Mitted","Bicolor"],["Deep blue"],3,2,2,2,5,5,4,"common",["longhair","popular","calm","large"],["blue-eyes","floppy","gentle","lap-cat"],["CFA","TICA","FIFe","GCCF"],["birman","ragamuffin","himalayan","maine-coon"],["birman","ragamuffin","maine-coon"],True,7))

B(mk("Russian Blue","russian-blue","Felis catus","The Russian Blue is elegant with a shimmering blue-gray coat, vivid green eyes, and a loyal personality.","Russia (Arkhangelsk)","15-20 years","10-15 lbs (4.5-6.8 kg)","7-10 lbs (3.2-4.5 kg)","9-10 inches (23-25 cm)","shorthair","Short, dense, plush double coat with silver tipping creating shimmer",["Blue-gray with silver tips"],["Solid"],["Vivid green"],2,2,3,2,3,3,5,"uncommon",["shorthair","popular","intelligent","hypoallergenic"],["blue-coat","russian-origin","hypoallergenic","emerald-eyes"],["CFA","TICA","FIFe","GCCF"],["chartreux","korat","nebelung","british-shorthair"],["chartreux","korat","nebelung"],True,9))

B(mk("Savannah","savannah","Felis catus x Leptailurus serval","The Savannah is a tall, striking hybrid breed with wild African serval ancestry and high intelligence.","United States","12-20 years","15-25 lbs (6.8-11.3 kg)","12-20 lbs (5.4-9.1 kg)","14-17 inches (36-43 cm)","shorthair","Short, dense, and spotted with a soft texture",["Brown spotted tabby","Silver spotted tabby","Black","Black smoke"],["Spotted","Marble"],["Green","Gold","Brown","Blue"],2,1,5,2,3,3,5,"rare",["shorthair","rare","large","intelligent","playful","hypoallergenic"],["hybrid","wild-ancestry","tallest-breed","dog-like"],["TICA"],["bengal","egyptian-mau","ocicat","abyssinian"],["bengal","serval"],False,100))

B(mk("Scottish Fold","scottish-fold","Felis catus","The Scottish Fold is famous for its unique folded-forward ears and owl-like, sweet expression.","United Kingdom (Scotland)","11-15 years","9-13 lbs (4.1-5.9 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","shorthair","Dense, plush, and soft teddy bear coat",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["Copper","Gold","Green","Blue","Odd-eyed"],3,2,2,2,5,5,4,"uncommon",["shorthair","popular","calm"],["folded-ears","owl-like","round-face","scottish-origin"],["CFA","TICA","FIFe","GCCF"],["british-shorthair","american-curl","scottish-straight"],["british-shorthair","american-curl"],True,11))

B(mk("Scottish Straight","scottish-straight","Felis catus","The Scottish Straight is the straight-eared variant of the Scottish Fold with the same sweet personality.","United Kingdom (Scotland)","11-15 years","9-13 lbs (4.1-5.9 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","shorthair","Dense, plush, and soft with straight ears",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["Copper","Gold","Green","Blue","Odd-eyed"],3,2,2,2,5,5,4,"uncommon",["shorthair","popular","calm"],["straight-ears","scottish-fold-relative","plush-coat"],["CFA"],["scottish-fold","british-shorthair","american-shorthair"],["scottish-fold","british-shorthair"],False,100))

B(mk("Selkirk Rex","selkirk-rex","Felis catus","The Selkirk Rex has a distinctively curly, plush coat nicknamed the cat in sheep's clothing.","United States","10-15 years","11-16 lbs (5-7.3 kg)","6-12 lbs (2.7-5.4 kg)","9-11 inches (23-28 cm)","shorthair","Curly, plush, and soft; dense with loose, individual ringlets",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],2,2,3,2,5,5,4,"uncommon",["shorthair","hypoallergenic","rare","calm"],["curly-coat","rex","plush","sheep-like"],["CFA","TICA","FIFe","GCCF"],["cornish-rex","devon-rex","british-shorthair","laperm"],["cornish-rex","british-shorthair","laperm"],False,100))

B(mk("Serengeti","serengeti","Felis catus","The Serengeti was bred to resemble a wild serval without any wild blood for a stunning spotted companion.","United States","10-15 years","10-15 lbs (4.5-6.8 kg)","8-12 lbs (3.6-5.4 kg)","10-12 inches (25-30 cm)","shorthair","Short, smooth, and close-lying with distinct spotting",["Gold spotted","Silver spotted","Black"],["Spotted tabby"],["Gold","Green"],2,1,5,3,4,4,5,"very-rare",["shorthair","rare","playful","large","intelligent"],["wild-look","spotted","serval-look","no-wild-blood"],["TICA"],["bengal","ocicat","oriental-shorthair","egyptian-mau"],["bengal","savannah","ocicat"],False,100))

B(mk("Siamese","siamese","Felis catus","The Siamese is a most recognizable breed with colorpoint markings, vivid blue eyes, and a famously talkative personality.","Thailand (Siam)","12-20 years","8-12 lbs (3.6-5.4 kg)","5-10 lbs (2.3-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Very short, fine, glossy, and close-lying",["Seal point","Blue point","Chocolate point","Lilac point"],["Colorpoint"],["Deep vivid blue"],1,1,4,5,4,3,5,"common",["shorthair","popular","vocal","intelligent"],["colorpoint","blue-eyes","talkative","elegant"],["CFA","TICA","FIFe","GCCF"],["balinese","oriental-shorthair","tonkinese","himalayan"],["balinese","oriental-shorthair","tonkinese"],True,10))

B(mk("Siberian","siberian","Felis catus","The Siberian is a large, powerful natural breed from Russia with a triple coat and notably hypoallergenic qualities.","Russia (Siberia)","12-15 years","15-20 lbs (6.8-9.1 kg)","10-15 lbs (4.5-6.8 kg)","9-11 inches (23-28 cm)","longhair","Thick, triple-layered, water-resistant; glossy and plush",["Brown tabby","All colors"],["Tabby","Solid","Tortoiseshell","Bicolor","Colorpoint"],["Gold","Green","Copper","Blue","Odd-eyed"],4,3,3,2,5,5,5,"uncommon",["longhair","popular","large","hypoallergenic","intelligent","playful"],["hypoallergenic","russian-origin","forest-cat","triple-coat"],["CFA","TICA","FIFe","GCCF"],["maine-coon","norwegian-forest-cat","ragdoll","neva-masquerade"],["maine-coon","norwegian-forest-cat"],True,13))

B(mk("Singapura","singapura","Felis catus","The Singapura is one of the smallest cat breeds with large expressive eyes and a ticked sepia coat.","Singapore","11-15 years","6-8 lbs (2.7-3.6 kg)","4-5 lbs (1.8-2.3 kg)","6-8 inches (15-20 cm)","shorthair","Very short, fine, silky, and close-lying",["Sepia agouti (ticked)"],["Ticked tabby"],["Hazel","Green","Gold"],1,1,5,3,4,4,5,"rare",["shorthair","rare","small","playful","intelligent"],["smallest-breed","ticked-coat","singapore-origin","big-eyes"],["CFA","TICA","FIFe"],["burmese","abyssinian","tonkinese","munchkin"],["abyssinian","burmese"],False,100))

B(mk("Snowshoe","snowshoe","Felis catus","The Snowshoe combines Siamese elegance with distinctive white feet and an affectionate, people-loving personality.","United States","12-15 years","9-14 lbs (4.1-6.4 kg)","7-10 lbs (3.2-4.5 kg)","8-13 inches (20-33 cm)","shorthair","Short, smooth, and close-lying",["Seal point with white","Blue point with white"],["Colorpoint with white markings"],["Deep blue"],2,1,3,3,5,5,5,"rare",["shorthair","rare","playful","intelligent"],["white-paws","siamese-relative","blue-eyes"],["TICA","CFA","FIFe"],["siamese","ragdoll","birman","tonkinese"],["siamese","ragdoll","birman"],False,100))

B(mk("Sokoke","sokoke","Felis catus","The Sokoke is a rare natural breed from Kenya with a unique marbled tabby coat and athletic build.","Kenya","10-15 years","6-10 lbs (2.7-4.5 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Short, close-lying, and glossy with no undercoat",["Brown marbled tabby"],["Marbled tabby"],["Green","Amber"],1,1,5,3,3,3,5,"very-rare",["shorthair","rare","playful","intelligent"],["marbled-tabby","african-origin","natural-breed"],["FIFe","TICA"],["bengal","egyptian-mau","abyssinian","ocicat"],["bengal","ocicat"],False,100))

B(mk("Somali","somali","Felis catus","The Somali is the longhaired version of the Abyssinian with a gorgeous ticked coat and fox-like plumed tail.","United States","11-16 years","10-14 lbs (4.5-6.4 kg)","7-10 lbs (3.2-4.5 kg)","9-11 inches (23-28 cm)","longhair","Medium-long, soft, fine, and double-coated with full ruff and plumed tail",["Ruddy","Red","Blue","Fawn"],["Ticked"],["Gold","Green","Amber"],3,3,5,2,4,4,5,"uncommon",["longhair","popular","playful","intelligent"],["ticked-coat","abyssinian-relative","fox-tail","active"],["CFA","TICA","FIFe","GCCF"],["abyssinian","bengal","ocicat","norwegian-forest-cat"],["abyssinian","maine-coon"],False,70))

B(mk("Sphynx","sphynx","Felis catus","The Sphynx is the iconic hairless breed known for wrinkled skin, large ears, and a warm, affectionate personality.","Canada","8-14 years","8-12 lbs (3.6-5.4 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","hairless","Hairless with fine peach-fuzz down; warm and soft like suede",["All colors and patterns (shown in skin pigment)"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors","Blue","Green","Gold","Odd-eyed"],1,3,5,3,5,5,5,"uncommon",["hairless","popular","hypoallergenic","playful","intelligent"],["hairless","large-ears","hypoallergenic","wrinkled"],["CFA","TICA","FIFe","GCCF"],["peterbald","don-sphynx","devon-rex","bambino"],["peterbald","devon-rex","don-sphynx"],True,14))

B(mk("Thai (Wichien Maat)","thai","Felis catus","The Thai, or Wichien Maat, is the original old-style Siamese from Thailand with a rounder, healthier build.","Thailand","12-17 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","9-12 inches (23-30 cm)","shorthair","Short, fine, glossy, and close-lying",["Seal point","Blue point","Chocolate point","Lilac point"],["Colorpoint"],["Deep blue"],2,1,4,4,4,4,5,"rare",["shorthair","rare","vocal","intelligent"],["traditional-siamese","thai-origin","colorpoint"],["TICA","FIFe","WCF"],["siamese","burmese","tonkinese","korat"],["siamese","burmese","tonkinese"],False,100))

B(mk("Tonkinese","tonkinese","Felis catus","The Tonkinese is a delightful blend of Siamese and Burmese with aqua eyes and a unique mink coat.","Canada / United States","12-16 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Short, soft, silky, and close-lying with mink-like texture",["Natural mink","Champagne mink","Blue mink","Platinum mink"],["Mink"],["Aqua","Blue-green","Green-blue"],1,1,4,4,5,4,5,"uncommon",["shorthair","popular","playful","intelligent"],["mink-coat","aqua-eyes","siamese-burmese-mix"],["CFA","TICA","FIFe","GCCF"],["siamese","burmese","burmilla","snowshoe"],["burmese","siamese","burmilla"],False,75))

B(mk("Tonkinese Longhair","tonkinese-longhair","Felis catus","The Tonkinese Longhair has the same aqua eyes and mink coat with a silky semi-long flowing coat.","United States","12-16 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","mediumhair","Semi-long, silky, and soft with mink texture",["Natural mink","Champagne mink","Blue mink","Platinum mink"],["Mink"],["Aqua","Blue-green","Green-blue"],2,2,4,4,5,4,5,"very-rare",["mediumhair","rare","vocal","intelligent"],["mink-coat","aqua-eyes","tonkinese-relative"],["TICA"],["tonkinese","siamese","burmese","balinese"],["tonkinese","balinese"],False,100))

B(mk("Toyger","toyger","Felis catus","The Toyger was bred to resemble a miniature tiger with dramatic black stripes on an orange background.","United States","10-15 years","10-15 lbs (4.5-6.8 kg)","7-10 lbs (3.2-4.5 kg)","9-13 inches (23-33 cm)","shorthair","Short, soft, lush, and plush with glitter effect",["Orange with black stripes"],["Mackerel tabby"],["Green","Gold"],2,1,4,2,5,4,5,"rare",["shorthair","rare","large","intelligent"],["tiger-stripes","designer-breed","glitter-coat"],["TICA"],["bengal","ocicat","egyptian-mau","savannah"],["bengal","ocicat"],False,100))

B(mk("Turkish Angora","turkish-angora","Felis catus","The Turkish Angora is an elegant ancient breed with a silky white coat and often mesmerizing odd-colored eyes.","Turkey (Ankara)","12-18 years","8-12 lbs (3.6-5.4 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","longhair","Semi-long, fine, silky, and shimmery; single coat prone to matting",["White","All colors"],["Solid","Tabby","Tortoiseshell","Bicolor","Smoke"],["Blue","Green","Gold","Amber","Odd-eyed"],3,3,4,3,4,4,5,"uncommon",["longhair","intelligent","playful"],["ancient-breed","turkish-origin","odd-eyed","silky-coat"],["CFA","TICA","FIFe","GCCF"],["turkish-van","maine-coon","somali","balinese"],["turkish-van","maine-coon"],False,80))

B(mk("Turkish Van","turkish-van","Felis catus","The Turkish Van is a rare ancient breed known for its love of water and distinctive color-restricted pattern.","Turkey (Lake Van region)","12-17 years","12-16 lbs (5.4-7.3 kg)","7-12 lbs (3.2-5.4 kg)","9-11 inches (23-28 cm)","mediumhair","Semi-long, soft, cashmere-like single coat; water-resistant",["White with auburn/red head and tail","White with cream","White with black","White with blue"],["Van pattern (color on head and tail only)"],["Blue","Green","Gold","Amber","Odd-eyed"],3,2,4,2,4,4,5,"rare",["mediumhair","rare","playful","large"],["swimming-cat","van-pattern","turkish-origin","water-loving"],["CFA","TICA","FIFe","GCCF"],["turkish-angora","maine-coon","norwegian-forest-cat"],["turkish-angora","maine-coon"],False,100))

B(mk("Ukrainian Levkoy","ukrainian-levkoy","Felis catus","The Ukrainian Levkoy is unique with inward-folding ears and a hairless body for a distinct alien-like appearance.","Ukraine","12-15 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","hairless","Hairless to light down; wrinkled skin with folded ears",["All skin colors"],["Solid","Patterned skin"],["All colors"],1,3,4,3,4,4,5,"very-rare",["hairless","rare","hypoallergenic","intelligent"],["hairless","folded-ears","ukrainian-origin","unique"],["WCF"],["sphynx","scottish-fold","peterbald"],["sphynx","peterbald"],False,100))

B(mk("York Chocolate","york-chocolate","Felis catus","The York Chocolate is a rare semi-longhaired breed with a rich chocolate brown coat and sweet personality.","United States","13-15 years","10-16 lbs (4.5-7.3 kg)","7-12 lbs (3.2-5.4 kg)","8-10 inches (20-25 cm)","mediumhair","Semi-long, silky, and glossy; rich chocolate or lavender",["Chocolate brown","Lavender"],["Solid chocolate"],["Green","Gold","Hazel"],3,2,3,2,5,4,4,"very-rare",["mediumhair","rare","calm"],["chocolate-coat","american-origin","rare","affectionate"],["WCF"],["havana-brown","burmese","british-shorthair"],["havana-brown","burmese"],False,100))

# ============================================================
# GENERATE ALL FILES
# ============================================================
print(f"Generating {len(BREEDS)} breed markdown files...")
for b in BREEDS:
    name = write_md(b)
    print(f"  {name} ({b['slug']})")

print(f"\nDone! {len(BREEDS)} breed files generated in {OUT}")
# Check american-shorthair.md exists separately (manually created with better content)
if os.path.exists(os.path.join(OUT, "american-shorthair.md")):
    print("Note: american-shorthair.md was not overwritten (pre-existing file)")