#!/usr/bin/env python3
"""Breeds data batch 2: P-Z"""

# Import the shared mk and gen_body from batch1
import sys
sys.path.insert(0, '.')
from gen_breeds_batch1 import mk, gen_body, write_md, BREEDS_DIR

B = globals().setdefault('BREEDS', __import__('gen_breeds_batch1').BREEDS).append

# === P ===
B(mk("Persian","persian","Felis catus","The Persian is one of the most recognizable cat breeds with its flat face and luxurious long coat. Discover this calm, regal breed.","Iran (Persia)","12-17 years","9-14 lbs (4.1-6.4 kg)","7-12 lbs (3.2-5.4 kg)","10-15 inches (25-38 cm)","longhair","Extremely long, thick, silky, and flowing with dense undercoat",["White","Black","Blue","Cream","Red","Silver","Golden"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint","Smoke"],["Copper","Blue","Green","Odd-eyed"],4,5,2,1,3,3,3,"common",["longhair","popular","calm"],["flat-face","luxurious-coat","calm","most-popular"],["CFA","TICA","FIFe","GCCF"],["himalayan","exotic-shorthair","ragdoll","birman"],["himalayan","exotic-shorthair","ragdoll"],True,6))

B(mk("Peterbald","peterbald","Felis catus","The Peterbald is an elegant hairless breed from Russia with a graceful build and affectionate nature. Discover this unique warm-to-touch breed.","Russia","12-15 years","7-14 lbs (3.2-6.4 kg)","6-10 lbs (2.7-4.5 kg)","8-12 inches (20-30 cm)","hairless","Hairless to velour to brush; varying degrees of hairlessness",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Colorpoint"],["All colors"],1,3,4,4,4,4,5,"rare",["hairless","rare","hypoallergenic","intelligent"],["hairless","russian-origin","oriental-type","hypoallergenic"],["TICA","FIFe","WCF"],["sphynx","don-sphynx","oriental-shorthair"],["sphynx","don-sphynx","oriental-shorthair"],False,100))

B(mk("Pixie-Bob","pixie-bob","Felis catus","The Pixie-Bob has a wild, bobcat-like appearance with a short tail and polydactyl paws. Discover this intelligent, dog-like American breed.","United States","13-15 years","8-22 lbs (3.6-10 kg)","8-12 lbs (3.6-5.4 kg)","9-13 inches (23-33 cm)","shorthair","Dense, wooly, and weather-resistant; stands off the body",["Brown spotted tabby"],["Spotted tabby"],["Gold","Brown","Green"],3,2,3,2,5,5,5,"rare",["shorthair","rare","large","intelligent"],["bobcat-look","bobbed-tail","polydactyl","dog-like"],["TICA"],["american-bobtail","maine-coon","norwegian-forest-cat"],["american-bobtail","maine-coon"],False,100))

# === R ===
B(mk("Ragamuffin","ragamuffin","Felis catus","The Ragamuffin is a large, fluffy breed with an exceptionally sweet, puppy-like personality. Discover this gentle giant companion.","United States","12-16 years","15-20 lbs (6.8-9.1 kg)","10-15 lbs (4.5-6.8 kg)","9-12 inches (23-30 cm)","longhair","Medium-long, dense, silky, and plush; rabbit-like texture",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Calico","Colorpoint"],["All colors","Blue"],4,3,2,2,5,5,4,"rare",["longhair","rare","calm","large"],["gentle-giant","puppy-like","fluffy","ragdoll-relative"],["CFA","TICA"],["ragdoll","birman","maine-coon","himalayan"],["ragdoll","maine-coon"],False,100))

B(mk("Ragdoll","ragdoll","Felis catus","The Ragdoll is famous for going limp when held and its stunning blue eyes. Discover this gentle, affectionate, and beautiful breed.","United States","12-17 years","12-20 lbs (5.4-9.1 kg)","8-15 lbs (3.6-6.8 kg)","9-11 inches (23-28 cm)","longhair","Semi-long, silky, soft with minimal undercoat; rabbit-like texture",["Seal","Blue","Chocolate","Lilac","Red","Cream"],["Colorpoint","Mitted","Bicolor"],["Deep blue"],3,2,2,2,5,5,4,"common",["longhair","popular","calm","large"],["blue-eyes","floppy","gentle","lap-cat"],["CFA","TICA","FIFe","GCCF"],["birman","ragamuffin","himalayan","maine-coon"],["birman","ragamuffin","maine-coon"],True,7))

B(mk("Russian Blue","russian-blue","Felis catus","The Russian Blue is an elegant breed with a shimmering blue-gray coat and vivid green eyes. Discover this intelligent, reserved, and loyal breed.","Russia (Arkhangelsk)","15-20 years","10-15 lbs (4.5-6.8 kg)","7-10 lbs (3.2-4.5 kg)","9-10 inches (23-25 cm)","shorthair","Short, dense, plush double coat with silver tipping creating shimmer",["Blue-gray with silver tips"],["Solid"],["Vivid green"],2,2,3,2,3,3,5,"uncommon",["shorthair","popular","intelligent","hypoallergenic"],["blue-coat","russian-origin","hypoallergenic","emerald-eyes"],["CFA","TICA","FIFe","GCCF"],["chartreux","korat","nebelung","british-shorthair"],["chartreux","korat","nebelung"],True,9))

# === S ===
B(mk("Savannah","savannah","Felis catus x Leptailurus serval","The Savannah is a tall, striking hybrid breed with wild African serval ancestry. Discover this highly intelligent and energetic exotic breed.","United States","12-20 years","15-25 lbs (6.8-11.3 kg)","12-20 lbs (5.4-9.1 kg)","14-17 inches (36-43 cm)","shorthair","Short, dense, and spotted with a soft texture",["Brown spotted tabby","Silver spotted tabby","Black","Black smoke"],["Spotted","Marble"],["Green","Gold","Brown","Blue"],2,1,5,2,3,3,5,"rare",["shorthair","rare","large","intelligent","playful","hypoallergenic"],["hybrid","wild-ancestry","tallest-breed","dog-like"],["TICA"],["bengal","egyptian-mau","ocicat","abyssinian"],["bengal","serval"],False,100))

B(mk("Scottish Fold","scottish-fold","Felis catus","The Scottish Fold is famous for its unique folded-forward ears and owl-like appearance. Discover this sweet, calm, and distinctive breed.","United Kingdom (Scotland)","11-15 years","9-13 lbs (4.1-5.9 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","shorthair","Dense, plush, and soft; also comes in longhair (Highland Fold)",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["Copper","Gold","Green","Blue","Odd-eyed"],3,2,2,2,5,5,4,"uncommon",["shorthair","popular","calm"],["folded-ears","owl-like","round-face","scottish-origin"],["CFA","TICA","FIFe","GCCF"],["british-shorthair","american-curl","scottish-straight"],["british-shorthair","american-curl"],True,11))

B(mk("Scottish Straight","scottish-straight","Felis catus","The Scottish Straight is the straight-eared variant of the Scottish Fold with the same sweet personality. Discover this charming, plush breed.","United Kingdom (Scotland)","11-15 years","9-13 lbs (4.1-5.9 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","shorthair","Dense, plush, and soft; straight ears",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["Copper","Gold","Green","Blue","Odd-eyed"],3,2,2,2,5,5,4,"uncommon",["shorthair","popular","calm"],["straight-ears","scottish-fold-relative","plush-coat"],["CFA"],["scottish-fold","british-shorthair","american-shorthair"],["scottish-fold","british-shorthair"],False,100))

B(mk("Selkirk Rex","selkirk-rex","Felis catus","The Selkirk Rex has a distinctively curly, plush coat and a patient, loving personality. Discover this unique 'cat in sheep's clothing' breed.","United States","10-15 years","11-16 lbs (5-7.3 kg)","6-12 lbs (2.7-5.4 kg)","9-11 inches (23-28 cm)","shorthair","Curly, plush, and soft; dense with loose ringlets",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],2,2,3,2,5,5,4,"uncommon",["shorthair","hypoallergenic","rare","calm"],["curly-coat","rex","plush","sheep-like"],["CFA","TICA","FIFe","GCCF"],["cornish-rex","devon-rex","british-shorthair","laperm"],["cornish-rex","british-shorthair","laperm"],False,100))

B(mk("Siamese","siamese","Felis catus","The Siamese is one of the most recognizable breeds with colorpoint markings, blue eyes, and a talkative personality. Discover this vocal, social breed.","Thailand (Siam)","12-20 years","8-12 lbs (3.6-5.4 kg)","5-10 lbs (2.3-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Very short, fine, glossy, and close-lying",["Seal point","Blue point","Chocolate point","Lilac point"],["Colorpoint"],["Deep vivid blue"],1,1,4,5,4,3,5,"common",["shorthair","popular","vocal","intelligent"],["colorpoint","blue-eyes","talkative","elegant"],["CFA","TICA","FIFe","GCCF"],["balinese","oriental-shorthair","tonkinese","himalayan"],["balinese","oriental-shorthair","tonkinese"],True,10))

B(mk("Siberian","siberian","Felis catus","The Siberian is a large, powerful natural breed from Russia with a triple coat and notably hypoallergenic qualities. Discover this majestic forest cat.","Russia (Siberia)","12-15 years","15-20 lbs (6.8-9.1 kg)","10-15 lbs (4.5-6.8 kg)","9-11 inches (23-28 cm)","longhair","Thick, triple-layered, water-resistant; glossy and plush",["Brown tabby","All colors"],["Tabby","Solid","Tortoiseshell","Bicolor","Colorpoint"],["Gold","Green","Copper","Blue","Odd-eyed"],4,3,3,2,5,5,5,"uncommon",["longhair","popular","large","hypoallergenic","intelligent","playful"],["hypoallergenic","russian-origin","forest-cat","triple-coat"],["CFA","TICA","FIFe","GCCF"],["maine-coon","norwegian-forest-cat","ragdoll","neva-masquerade"],["maine-coon","norwegian-forest-cat"],True,13))

B(mk("Singapura","singapura","Felis catus","The Singapura is one of the smallest cat breeds with large eyes and a ticked coat. Discover this tiny, energetic, and loving breed from Singapore.","Singapore","11-15 years","6-8 lbs (2.7-3.6 kg)","4-5 lbs (1.8-2.3 kg)","6-8 inches (15-20 cm)","shorthair","Very short, fine, silky, and close-lying",["Sepia agouti (ticked)"],["Ticked tabby"],["Hazel","Green","Gold"],1,1,5,3,4,4,5,"rare",["shorthair","rare","small","playful","intelligent"],["smallest-breed","ticked-coat","singapore-origin","big-eyes"],["CFA","TICA","FIFe"],["burmese","abyssinian","tonkinese","munchkin"],["abyssinian","burmese"],False,100))

B(mk("Snowshoe","snowshoe","Felis catus","The Snowshoe combines Siamese elegance with distinctive white feet and an affectionate, people-loving personality. Discover this charming breed.","United States","12-15 years","9-14 lbs (4.1-6.4 kg)","7-10 lbs (3.2-4.5 kg)","8-13 inches (20-33 cm)","shorthair","Short, smooth, and close-lying",["Seal point with white","Blue point with white"],["Colorpoint with white markings"],["Deep blue"],2,1,3,3,5,5,5,"rare",["shorthair","rare","playful","intelligent"],["white-paws","siamese-relative","blue-eyes"],["TICA","CFA","FIFe"],["siamese","ragdoll","birman","tonkinese"],["siamese","ragdoll","birman"],False,100))

B(mk("Somali","somali","Felis catus","The Somali is the longhaired version of the Abyssinian with a gorgeous ticked coat and fox-like tail. Discover this active, playful breed.","United States","11-16 years","10-14 lbs (4.5-6.4 kg)","7-10 lbs (3.2-4.5 kg)","9-11 inches (23-28 cm)","longhair","Medium-long, soft, fine, and double-coated with full ruff and plumed tail",["Ruddy","Red","Blue","Fawn"],["Ticked"],["Gold","Green","Amber"],3,3,5,2,4,4,5,"uncommon",["longhair","popular","playful","intelligent"],["ticked-coat","abyssinian-relative","fox-tail","active"],["CFA","TICA","FIFe","GCCF"],["abyssinian","bengal","ocicat","norwegian-forest-cat"],["abyssinian","maine-coon"],False,70))

B(mk("Sphynx","sphynx","Felis catus","The Sphynx is the iconic hairless cat breed known for its wrinkled skin, large ears, and warm, affectionate personality. Discover this unique breed.","Canada","8-14 years","8-12 lbs (3.6-5.4 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","hairless","Hairless with fine peach-fuzz down; warm and soft to touch",["All colors and patterns (shown in skin pigment)"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors","Blue","Green","Gold","Odd-eyed"],1,3,5,3,5,5,5,"uncommon",["hairless","popular","hypoallergenic","playful","intelligent"],["hairless","large-ears","hypoallergenic","wrinkled"],["CFA","TICA","FIFe","GCCF"],["peterbald","don-sphynx","devon-rex","bambino"],["peterbald","devon-rex","don-sphynx"],True,14))

# === T ===
B(mk("Tonkinese","tonkinese","Felis catus","The Tonkinese is a delightful blend of Siamese and Burmese with aqua eyes and a mink coat. Discover this loving, playful, and beautiful breed.","Canada / United States","12-16 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Short, soft, silky, and close-lying with a mink-like texture",["Natural mink","Champagne mink","Blue mink","Platinum mink"],["Mink (unique to Tonkinese)"],["Aqua","Blue-green","Green-blue"],1,1,4,4,5,4,5,"uncommon",["shorthair","popular","playful","intelligent"],["mink-coat","aqua-eyes","siamese-burmese-mix"],["CFA","TICA","FIFe","GCCF"],["siamese","burmese","burmilla","snowshoe"],["burmese","siamese","burmilla"],False,75))

B(mk("Toyger","toyger","Felis catus","The Toyger was bred to resemble a miniature tiger with dramatic black stripes on an orange background. Discover this stunning designer breed.","United States","10-15 years","10-15 lbs (4.5-6.8 kg)","7-10 lbs (3.2-4.5 kg)","9-13 inches (23-33 cm)","shorthair","Short, soft, lush, and plush with glitter effect",["Orange with black stripes"],["Mackerel tabby (vertical stripes)"],["Green","Gold"],2,1,4,2,5,4,5,"rare",["shorthair","rare","large","intelligent"],["tiger-stripes","designer-breed","glitter-coat"],["TICA"],["bengal","ocicat","egyptian-mau","savannah"],["bengal","ocicat"],False,100))

B(mk("Turkish Angora","turkish-angora","Felis catus","The Turkish Angora is an elegant, ancient breed with a silky white coat and often odd-colored eyes. Discover this graceful, intelligent breed.","Turkey (Ankara)","12-18 years","8-12 lbs (3.6-5.4 kg)","6-9 lbs (2.7-4.1 kg)","8-10 inches (20-25 cm)","longhair","Semi-long, fine, silky, and shimmery; prone to matting if not groomed",["White (most iconic)","All colors"],["Solid","Tabby","Tortoiseshell","Bicolor","Smoke"],["Blue","Green","Gold","Amber","Odd-eyed common"],3,3,4,3,4,4,5,"uncommon",["longhair","intelligent","playful"],["ancient-breed","turkish-origin","odd-eyed","silky-coat"],["CFA","TICA","FIFe","GCCF"],["turkish-van","maine-coon","somali","balinese"],["turkish-van","maine-coon"],False,80))

B(mk("Turkish Van","turkish-van","Felis catus","The Turkish Van is a rare, ancient breed known for its love of water and distinctive color-restricted-to-head-and-tail pattern. Discover this swimming cat.","Turkey (Lake Van region)","12-17 years","12-16 lbs (5.4-7.3 kg)","7-12 lbs (3.2-5.4 kg)","9-11 inches (23-28 cm)","mediumhair","Semi-long, soft, cashmere-like single coat; water-resistant",["White with auburn/red head and tail","White with cream","White with black","White with blue"],["Van pattern (color on head and tail only)"],["Blue","Green","Gold","Amber","Odd-eyed"],3,2,4,2,4,4,5,"rare",["mediumhair","rare","playful","large"],["swimming-cat","van-pattern","turkish-origin","water-loving"],["CFA","TICA","FIFe","GCCF"],["turkish-angora","maine-coon","norwegian-forest-cat"],["turkish-angora","maine-coon"],False,100))

# === U-Z ===
B(mk("Ukrainian Levkoy","ukrainian-levkoy","Felis catus","The Ukrainian Levkoy is a unique breed with inward-folding ears and a hairless body. Discover this distinctive, affectionate breed.","Ukraine","12-15 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","hairless","Hairless to light down; wrinkled skin",["All skin colors"],["Solid","Patterned skin"],["All colors"],1,3,4,3,4,4,5,"very-rare",["hairless","rare","hypoallergenic","intelligent"],["hairless","folded-ears","ukrainian-origin","unique"],["WCF"],["sphynx","scottish-fold","peterbald"],["sphynx","peterbald"],False,100))

B(mk("York Chocolate","york-chocolate","Felis catus","The York Chocolate is a rare semi-longhaired breed with a rich brown coat. Discover this sweet, affectionate American breed.","United States","13-15 years","10-16 lbs (4.5-7.3 kg)","7-12 lbs (3.2-5.4 kg)","8-10 inches (20-25 cm)","mediumhair","Semi-long, silky, and glossy; rich chocolate or lavender",["Chocolate brown","Lavender"],["Solid chocolate"],["Green","Gold","Hazel"],3,2,3,2,5,4,4,"very-rare",["mediumhair","rare","calm"],["chocolate-coat","american-origin","rare","affectionate"],["WCF"],["havana-brown","burmese","british-shorthair"],["havana-brown","burmese"],False,100))

# === More Breeds ===
B(mk("Chantilly-Tiffany","chantilly-tiffany","Felis catus","The Chantilly-Tiffany is a rare semi-longhair with a rich chocolate coat and golden eyes. Discover this mysterious, sweet breed.","United States","11-15 years","8-14 lbs (3.6-6.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","mediumhair","Semi-long, silky, and soft; does not mat easily",["Chocolate","Cinnamon","Fawn","Blue"],["Solid"],["Gold","Yellow"],2,2,3,2,4,4,4,"very-rare",["mediumhair","rare","calm"],["chocolate-coat","rare-breed","sweet","semi-longhair"],["ACFA"],["burmese","havana-brown","turkish-angora"],["burmese","havana-brown"],False,100))

B(mk("Colorpoint Shorthair","colorpoint-shorthair","Felis catus","The Colorpoint Shorthair is essentially a Siamese in non-traditional point colors. Discover this elegant, vocal, and affectionate breed.","United States","12-15 years","8-12 lbs (3.6-5.4 kg)","5-10 lbs (2.3-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Very short, fine, glossy, and close-lying",["Red point","Cream point","Lynx point","Tortie point"],["Colorpoint"],["Deep vivid blue"],1,1,4,5,4,3,5,"uncommon",["shorthair","vocal","intelligent","playful"],["colorpoint","siamese-relative","vocal"],["CFA","TICA"],["siamese","balinese","oriental-shorthair","javanese"],["siamese","balinese"],False,100))

B(mk("Highlander","highlander","Felis catus","The Highlander is a unique breed with curled ears, a short tail, and a wild appearance. Discover this active, playful, and unusual breed.","United States","10-15 years","10-20 lbs (4.5-9.1 kg)","8-14 lbs (3.6-6.4 kg)","10-14 inches (25-36 cm)","shorthair","Short to medium; also comes in longhair",["All colors and patterns"],["Tabby","Solid","Tortoiseshell","Bicolor"],["All colors"],3,2,4,2,4,4,5,"very-rare",["shorthair","rare","playful","large"],["curled-ears","bobbed-tail","wild-look","hybrid"],["TICA"],["american-curl","american-bobtail","bengal"],["american-bobtail","bengal"],False,100))

B(mk("Minskin","minskin","Felis catus","The Minskin is a short-legged breed with sparse fur points. Discover this tiny, affectionate, and unique designer breed.","United States","12-15 years","4-6 lbs (1.8-2.7 kg)","4-6 lbs (1.8-2.7 kg)","5-7 inches (13-18 cm)","hairless","Sparse fur mainly on points (face, ears, legs, tail); body nearly hairless",["All colors and patterns"],["Point-restricted fur"],["All colors"],1,2,3,2,5,4,4,"very-rare",["hairless","rare","playful"],["short-legs","hairless","designer-breed","small"],["TICA"],["munchkin","sphynx","bambino","devon-rex"],["munchkin","sphynx","bambino"],False,100))

B(mk("Napoleon (Minuet)","minuet","Felis catus","The Napoleon (Minuet) combines Munchkin short legs with Persian-like beauty. Discover this small, sweet, and cuddly breed.","United States","12-15 years","5-9 lbs (2.3-4.1 kg)","5-8 lbs (2.3-3.6 kg)","5-7 inches (13-18 cm)","shorthair","Dense, plush; also comes in longhair",["All colors and patterns"],["Solid","Tabby","Tortoiseshell","Bicolor","Colorpoint"],["All colors"],3,2,2,2,5,5,4,"very-rare",["shorthair","rare","calm","small"],["short-legs","persian-type","cuddly","designer-breed"],["TICA"],["munchkin","persian","exotic-shorthair"],["munchkin","exotic-shorthair"],False,100))

B(mk("Serengeti","serengeti","Felis catus","The Serengeti was bred to resemble a wild serval without wild blood. Discover this athletic, graceful, and active breed.","United States","10-15 years","10-15 lbs (4.5-6.8 kg)","8-12 lbs (3.6-5.4 kg)","10-12 inches (25-30 cm)","shorthair","Short, smooth, and close-lying with distinct spotting",["Gold spotted","Silver spotted","Black"],["Spotted tabby"],["Gold","Green"],2,1,5,3,4,4,5,"very-rare",["shorthair","rare","playful","large","intelligent"],["wild-look","spotted","serval-look","no-wild-blood"],["TICA"],["bengal","ocicat","oriental-shorthair","egyptian-mau"],["bengal","savannah","ocicat"],False,100))

B(mk("Sokoke","sokoke","Felis catus","The Sokoke is a rare natural breed from Kenya with a unique marbled tabby coat. Discover this athletic, intelligent African breed.","Kenya","10-15 years","6-10 lbs (2.7-4.5 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","shorthair","Short, close-lying, and glossy with no undercoat",["Brown marbled tabby"],["Marbled tabby (unique pattern)"],["Green","Amber"],1,1,5,3,3,3,5,"very-rare",["shorthair","rare","playful","intelligent"],["marbled-tabby","african-origin","natural-breed","rare"],["FIFe","TICA"],["bengal","egyptian-mau","abyssinian","ocicat"],["bengal","ocicat"],False,100))

B(mk("Thai (Wichien Maat)","thai","Felis catus","The Thai, or Wichien Maat, is the original old-style Siamese from Thailand. Discover this rounder, healthier traditional Siamese type.","Thailand","12-17 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","9-12 inches (23-30 cm)","shorthair","Short, fine, glossy, and close-lying",["Seal point","Blue point","Chocolate point","Lilac point"],["Colorpoint"],["Deep blue"],2,1,4,4,4,4,5,"rare",["shorthair","rare","vocal","intelligent"],["traditional-siamese","thai-origin","colorpoint"],["TICA","FIFe","WCF"],["siamese","burmese","tonkinese","korat"],["siamese","burmese","tonkinese"],False,100))

B(mk("Tonkinese Longhair","tonkinese-longhair","Felis catus","The Tonkinese Longhair (Tiffany) has the same aqua eyes and mink coat as the shorthair variety but with a silky semi-long coat.","United States","12-16 years","8-12 lbs (3.6-5.4 kg)","6-10 lbs (2.7-4.5 kg)","8-10 inches (20-25 cm)","mediumhair","Semi-long, silky, and soft with mink texture",["Natural mink","Champagne mink","Blue mink","Platinum mink"],["Mink"],["Aqua","Blue-green","Green-blue"],2,2,4,4,5,4,5,"very-rare",["mediumhair","rare","vocal","intelligent"],["mink-coat","aqua-eyes","tonkinese-relative"],["TICA"],["tonkinese","siamese","burmese","balinese"],["tonkinese","balinese"],False,100))

B(mk("Bambino","bambino","Felis catus","The Bambino combines the Sphynx hairlessness with Munchkin short legs. Discover this tiny, warm, and affectionate designer breed.","United States","9-14 years","5-9 lbs (2.3-4.1 kg)","4-7 lbs (1.8-3.2 kg)","5-7 inches (13-18 cm)","hairless","Hairless with peach-fuzz down; wrinkled and warm",["All skin colors and patterns"],["Solid","Patterned"],["All colors","Blue","Green","Gold"],1,3,4,2,5,4,4,"very-rare",["hairless","rare","playful"],["hairless","short-legs","designer-breed","warm"],["TICA (Experimental)"],["sphynx","munchkin","minskin","peterbald"],["sphynx","munchkin","minskin"],False,100))

B(mk("Cheetoh","cheetoh","Felis catus","The Cheetoh is a large hybrid breed combining Bengal spots with Ocicat size. Discover this wild-looking, gentle giant breed.","United States","12-16 years","15-23 lbs (6.8-10.4 kg)","12-18 lbs (5.4-8.2 kg)","12-18 inches (30-46 cm)","shorthair","Short, soft, dense, and rosetted",["Brown spotted","Silver spotted","Snow spotted","Gold spotted"],["Spotted/Rosetted"],["Green","Gold","Hazel","Blue (snow)"],2,1,4,2,4,4,5,"very-rare",["shorthair","rare","large","playful","intelligent"],["rosetted","large","bengal-ocicat-hybrid","wild-look"],["TICA (Experimental)"],["bengal","ocicat","savannah","toyger"],["bengal","savannah","ocicat"],False,100))

B(mk("Dwelf","dwelf","Felis catus","The Dwelf is a rare designer breed combining hairlessness, curled ears, and short legs. Discover this tiny, elf-like companion.","United States","10-15 years","4-7 lbs (1.8-3.2 kg)","4-6 lbs (1.8-2.7 kg)","5-7 inches (13-18 cm)","hairless","Hairless with fine down; curled ears and short legs",["All skin colors"],["Solid","Patterned"],["All colors"],1,3,3,2,4,4,4,"very-rare",["hairless","rare","playful"],["hairless","curled-ears","short-legs","elf-like"],["TICA (Experimental)"],["sphynx","munchkin","american-curl","bambino"],["sphynx","bambino","minskin"],False,100))

print(f"Batch 2 breeds loaded. Total now: {len([b for b in __import__('sys').modules[__name__].__dict__.values() if isinstance(b, dict)])}")